/// <reference types="cypress" />

context('Múltiplas Empresas de Cobrança', () => {

    beforeEach(function () {
        cy.visit('/')
        cy.viewport(1366, 768)
        cy.fixture("dados-mec").as('mec').then(() => {})
    })

    it('I - Cadastro de Regra - Graduação Presencial - SCA Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            //pedir para colocar um identificador no botão que expande o menu lateral
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            //pedir para colocar um identificador nas abas que abrem as opções de menu
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            //pedir para colcoar um identificador nas opções do menu lateral após expandir a aba
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Direito Noturno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            //Pedir para colocar identificador no botão SALVAR
            //Pedir para colocar idenfiticador no botão CANCELAR
    });

    it('II - Cadastro de Regra - Graduação Presencial - SCA Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Odontologia - Integral{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('III - Cadastro de Regra - Ensino a Distância - EAD Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Educação Física{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Tecnologia em Estética e Cosmética{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('IV - Cadastro de Regra - Ensino a Distância - EAD Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Pedagogia{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('V - Cadastro de Regra - Pós-Graduação Lato Sensu - SPGL Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Pós-Graduação Lato Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Engenharia de Segurança do Trabalho{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Tricologia e Terapia Capilar{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('VI - Cadastro de Regra - Pós-Graduação Lato Sensu - SPGL Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Pós-Graduação Lato Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Todos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break) 
    });

    it('VII - Cadastro de Regra - Pós-Graduação Stricto Sensu - SIP Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Pós-Graduação Stricto Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Mestrado em Direitos Humanos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Doutorado em Saúde e Ambiente{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('VIII - Cadastro de Regra - Pós-Graduação Stricto Sensu - SIP Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Pós-Graduação Stricto Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Mestrado em Direitos Humanos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Doutorado em Educação{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break) 
    });

    it('VIII - Cadastro de Regra - Pós-Graduação Stricto Sensu - SIP Parcelas', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Pós-Graduação Stricto Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Mestrado em Direitos Humanos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Doutorado em Educação{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('IX - Cadastro de Regra - Títulos Avulsos 03 - Negociação', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Direito Noturno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Negociação{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('X - Cadastro de Regra - Títulos Avulsos 03 - Negociação', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            //Colocar qual é o curso exato de Educação Física
            .get('input[name="curso"]').type('Educação Física{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Negociação{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('XI - Cadastro de Regra - Títulos Avulsos 05 - Parcelamento em boletos', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Abandonado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Pedagogia{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Parcelamento em Boletos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)   
    });

    it('XII - Cadastro de Regra - Títulos Avulsos 06 - Antecipação de matrícula', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Antecipação de matrícula{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)   
    });

    it('XIII - Cadastro de Regra - Títulos Avulsos - 07 - Antec. de matrícula - 5x', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Abandonado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Pedagogia{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Antecipação de matrícula{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('XIV - Cadastro de Regra - Títulos Avulsos - 11 - Títulos pendentes 2020.1', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Stricto Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Mestrado em Direitos Humanos{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('pendentes 2020.1{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)     
    });

    it('XV - Cadastro de Regra - Títulos Avulsos - 12 - Cont. Cartão Crédito', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Nutrição - Manhã{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Engenharia de Produção - Noite{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Cont. Cartão Crédito{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)   
    });

    it('XVI - Cadastro de Regra - Títulos Avulsos - 13 - Cheques. Devolv', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Abandonado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Direito Noturno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Engenharia Civil - Noite{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Enfermagem - Manhã/Tarde{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Enfermagem - Tarde/Noite{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Cheques. Devolv{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)    
    });

    it('XVII - Cadastro de Regra - Títulos Avulsos - 15 - Título de Oferta especial 2', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Odontologia - Integral{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Enfermagem - Tarde/Noite{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Título de Oferta especial 2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)  
    });

    it('XVIII - Cadastro de Regra - Títulos Avulsos - 16 - Cont. Cartão Crédito(10x)', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Ensino a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Abandonado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Educação Física{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Cartão Crédito(10x){enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)  
    });

    it('XIX - Cadastro de Regra - Títulos Avulsos - 16 - Cont. Cartão Crédito(10x)', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Cheques. Devolv. (5x){enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    });

    it('XX - Cadastro de Regra - Títulos Avulsos - 21 - Titulo Oferta Espec 2 - Ajuste', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Titulo Oferta Espec 2 – Ajuste{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    });

    it('XXI - Cadastro de Regra - Títulos Avulsos - 22 - Título desconto duplicado-SPGL', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Lato Sensu{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Didática, Docência e Tutoria na Educação a Distância{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Enfermagem Obstétrica{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('desconto duplicado-SPGL{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    });

    it('XXIII - Cadastro de Regra - Títulos Avulsos - 24 - Título de Negociação', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Matriculado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Nutrição - Manhã{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Título de Negociação{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    });

    it('XXIV - Cadastro de Regra - Devolução de Cheque', function () {
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Graduação Presencial{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Devolução de Cheque{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Trancado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Formado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="situacao"]').type('Abandonado{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Medicina{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Enfermagem - Manhã/Tarde{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Odontologia - Integral{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Direito Noturno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('Gastronomia - Noite{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tituloAvulso"]').type('Título de Negociação{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    });

    /* it('XXV - Cadastro de Regra - Atividade de Extensão', function () {
    //Esse caso de teste não está completo
    //Falta terminar os cursos no campo    
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Extensão{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Parcela do Curso do Aluno{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
        //Os cursos não estão sendo apresentados para a seleção    
            .get('input[name="curso"]').type('A2 Elementary English (Level 4) -Sexta-18h45 às 21h15 Teacher: Anderson{downarrow}{enter}', {delay: 500}, {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('B2 Upper-Intermediate English (Level 9) -Sábado- 10h30 às 13h00 Teacher Gilberto{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('B1 Pre-Intermediate English (Level 6) -Quarta -18h45 às 21h15 Teacher: Cristal{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('B2 Upper-Intermediate English(Level 9)- Segunda- 14h00 às 16h30 - Teacher Gilberto{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
        //    
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    }); */

    /* it.only('XXVI - Cadastro de Regra - Títulos Avulsos - 05 - Parcelamento em boletos', function () {   
    //Esse caso de teste não está completo
    //Falta terminar os cursos no campo     
        cy.url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/')
            .get('.jss12 > .jss22 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
            .get('span').contains('Regras').click()
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras')
            .get('span').contains('Cadastro de Regras').click()
            .wait(this.mec.break)
            .url().should('eq', 'https://mecfrontendhomologacao.grupotiradentes.com/regras/cadastrar')
            .wait(this.mec.break)
            .get('input[name="instituicao"]').type('unit{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="modalidade"]').type('Extensão{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="tipoTitulo"]').type('Título Avulso{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
    //Os cursos não estão sendo apresentados para a seleção             
            .get('input[name="curso"]').type('A1 Beginner English{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('NATAÇÃO{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="curso"]').type('A2 Elementary English (Level 3) - Terça-18h45 às 21h15{downarrow}{enter}', {force: true})
            .wait(this.mec.break)
    //    
            .get('input[name="inadimplenciaInicial"]').type('01012021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="inadimplenciaFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeInicial"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="validadeFinal"]').type('09022021{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaAVista"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorAVista"]').type('30{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaCartao"]').type('45{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorCartao"]').type('25{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasCartao"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentJurosMultaBoleto"]').type('20{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentValorBoleto"]').type('40{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="percentEntradaBoleto"]').type('35{enter}', {force: true})
            .wait(this.mec.break)
            .get('input[name="quantidadeParcelasBoleto"]').type('2{enter}', {force: true})
            .wait(this.mec.break)
    }); */

})